project './MediaFramework/MediaFramework.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MediaFramework' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for MediaFramework
  pod "GPUImage"
  
  pod 'Masonry', '1.0.2'
  pod 'SVProgressHUD', '2.1.2'
end
